logging:
  level:
    root: error
    org:
      hibernate:
        type: error
        sql: TRACE
spring:
  jpa:
    open-in-view: off
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: create





